# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 2, 18, 16, 918934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
